# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87fa0c9d3234e604d572be44fe1ec02690346e43b977913c75ef8137bfd481e7bd3c9719c138498c8871c52b0396eebacf77af9faa2546255bf3771ecacdb49a

test:
  secret_key_base: a73184b63ae08b14544a14b7221cbf8403c53afc57b4e22fb4eb178ddcede1777ae8dc5e229a053c9f09403a2727a12e030f3687cac428c49be512ec69d650d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
